### PR TITLE
Visual + code cleanup, added new title text and new Take Action pop up

### PR DESCRIPTION
**Pull request by clay-to-n**
Simple fix of the title text in regards to issue #3.  Would love to help with more but, after npm install'ing, when I run 'node app.js' I get an error from config.js from line 13, which just prints 'Missing environment variable key'

### CODE REVIEW

**Comment by austinEng** [comment]
You need to make a copy of config.template.json and rename it to config.json.
Then you need to fill in the appropriate fields
This is the information which the app uses to connect to google spreadsheet where the information is stored

key: the spreadsheet key. (urls for spreadsheets are usually docs.google.com/spreadsheets/d/KEY) or something like that

email: the email address that can access the spreadsheet
password: the respective password

**Comment by clay-to-n** [comment]
Great, thanks. I'll try to dig into more stuff this week.

**Comment by choquette33** [comment]
Thanks for your help @clay-to-n!

**Comment by clay-to-n** [comment]
Okay, so I got it running by running node, mongo, and giving the link of a google spreadsheet.

Is there a certain format the spreadsheet must be in?  I was digging in pretty deep but never got it 100% working - I just commented out the leaderboard-displaying the html at a certain point, and worked from there.

**Comment by clay-to-n** [comment]
Did a bunch of cleanup and styling.  I had to comment out the leaderboard display (and a bit in the js files) to run on my machine, but I believe I undid everything related to that.  So it's mostly cosmetic.  

Also added a Readme with simple contributing instructions.  If you follow those exactly, you get the same errors I did and need to comment out a few sections of code to get it to run.  I think the problem was that I didn't know what format the spreadsheet needed to be in - I made columns for "count", "name", "edits", and "whatisyouropenstreetmapusername" (and only used real accounts), but I still got errors so I gave up on that front.  It would be nice to include a description on how a contributor can make their own, or have one online to look at.  Or even just include some fixture option so that when developing you just load the data from a json file or similar.

Anyways, not quite sure how much use this site is even getting, but I saw the Help Wanted tags and wanted to do some brainless styling.  Cheers.

close #4 close #3

**Comment by choquette33** [comment]
@clay-to-n Thanks a lot! We are using this site as is, and usage will only increase as we smooth it out a bit.

**Comment by choquette33** [comment]
@austinEng Could you help with the push to Heroku? I only have my chromebook now and don't know how to access the command line/terminal to do the push.

**Pull request merged**
